<a href="https://colab.research.google.com/github/akshata-data/Python-projects/blob/main/input.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df=pd.read_csv("/content/Input.csv",parse_dates=["date"])

In [2]:
df

   employee_id     name        date status
0          101  Akshata  2026-07-15      P
1          102     Ravi  2026-07-15      A
2          103     John  2026-07-15      P
3          101  Akshata  2026-07-15      P
4          104    Meena  2026-07-15    NaN

Remove duplicates

In [4]:
df.drop_duplicates(inplace=True)

In [6]:
df

   employee_id     name       date status
0          101  Akshata 2026-07-15      P
1          102     Ravi 2026-07-15      A
2          103     John 2026-07-15      P
4          104    Meena 2026-07-15    NaN

Fill missing attendance status

In [8]:
df.fillna("Absent",inplace=True)

In [9]:
df

   employee_id     name        date  status
0          101  Akshata  2026-07-15       P
1          102     Ravi  2026-07-15       A
2          103     John  2026-07-15       P
4          104    Meena  2026-07-15  Absent

Convert status

In [7]:
df["status"]=df["status"].map({"P":"Present","A":"Absent"})

In [13]:
df

   employee_id     name        date   status
0          101  Akshata  2026-07-15  Present
1          102     Ravi  2026-07-15   Absent
2          103     John  2026-07-15  Present
4          104    Meena  2026-07-15      NaN

In [8]:
df.fillna("Absent",inplace=True)

In [15]:
df

   employee_id     name        date   status
0          101  Akshata  2026-07-15  Present
1          102     Ravi  2026-07-15   Absent
2          103     John  2026-07-15  Present
4          104    Meena  2026-07-15   Absent

 Generate Summary

In [9]:
total_emp = len(df)
present_emp = (df["status"]=="Present").sum()
absent_emp = (df["status"]=="Absent").sum()
per_attendence = present_emp/total_emp*100
df["date"] = pd.to_datetime(df["date"])
date = df["date"].iloc[0].date()

In [10]:
with open("summary.txt","w") as f:
  f.write(f"Date          :{date}\n")
  f.write(f"Total employee: {total_emp}\n")
  f.write(f"Present       : {present_emp}\n")
  f.write(f"Absent        : {absent_emp}\n")
  f.write(f"Attendence %  : {per_attendence}%")

In [11]:
with open("summary.txt","r") as f:
  summary = f.read()
print(summary)

Date          :2026-07-15
Total employee: 4
Present       : 2
Absent        : 2
Attendence %  : 50.0%